-- AlterTable
ALTER TABLE "PropertyType" ADD COLUMN     "basePrice" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "kamarMandi" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "kamarTidur" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Unit" ADD COLUMN     "kawasan" TEXT NOT NULL DEFAULT 'Area 1',
ADD COLUMN     "nomor" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "priceMarkup" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "statusPembangunan" TEXT NOT NULL DEFAULT 'Pesan Bangun',
ADD COLUMN     "statusPenjualan" TEXT NOT NULL DEFAULT 'Tersedia',
ADD COLUMN     "totalPrice" DOUBLE PRECISION NOT NULL DEFAULT 0;
